# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

df = pd.read_csv("bank.csv", sep=";")

print(df)

df.dtypes

df.head()

df.isna().sum()

df.duplicated().sum()



# prompt: convert all categorical column in to numeric values

# Convert categorical columns to numerical using Label Encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

print(df.head())



x = df.drop('y', axis=1)
y = df['y'] # Use square brackets to select the column 'y'

# prompt: split the x and y for train and testing

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

