# -*- coding: utf-8 -*-
"""Decision Tree

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J98TLjkGVyyCO4D2U9DusrTzE6vt4FFw
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn import tree
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

# Assuming your file is called 'data.csv'
df = pd.read_csv('diabetes.csv')
df.head()

# Example: Assuming the last column is the target
X = df.iloc[:, :-1]  # features
y = df.iloc[:, -1]   # target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

clf = DecisionTreeClassifier(criterion="entropy", random_state=42)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

plt.figure(figsize=(20,10))
tree.plot_tree(clf, filled=True, feature_names=X.columns, class_names=['0','1']) # Assuming your target variable has values 0 and 1
plt.show()

